/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package doan;

import java.sql.ResultSet;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author phong
 */
public class Chuyen_Tien extends javax.swing.JFrame {

    Login l = new Login();
    private String tenTK = l.user_dang_nhap;

    public Chuyen_Tien() {
        initComponents();
    }

    public float SoTienTrongTaiKhoan() {
        float fTien = 0;
        try {
            ConnectionDB con = new ConnectionDB();
            String sql = "select * from UserN where username='" + tenTK + "'";

            ResultSet rs = con.s.executeQuery(sql);
            while (rs.next()) {
                fTien = Float.parseFloat(rs.getString("SoTienTaiKhoan"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Loi " + e);
        }
        return fTien;
    }

    public int KiemTraTaiKhoan(String userNguoiNhan) {
        int check = 0;
        try {
            ConnectionDB con = new ConnectionDB();
            String sql = "SELECT * FROM DangNhap WHERE username ='" + userNguoiNhan + "'";

            ResultSet rs = con.s.executeQuery(sql);
            if (rs.next()) {
                check = 1;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Loi " + e);
        }
        return check;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_Tai_Khoan_Nhan = new javax.swing.JTextField();
        txt_So_Tien_Chuyen = new javax.swing.JTextField();
        btn_Back = new javax.swing.JButton();
        btn_OK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("Chuyển Tiền");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Tài khoản nhận tiền :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Số tiền chuyển :");

        txt_Tai_Khoan_Nhan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        txt_So_Tien_Chuyen.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_So_Tien_Chuyen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_So_Tien_ChuyenMouseClicked(evt);
            }
        });

        btn_Back.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_Back.setText("Back");
        btn_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BackActionPerformed(evt);
            }
        });

        btn_OK.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_OK.setText("OK");
        btn_OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_OKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_So_Tien_Chuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Tai_Khoan_Nhan, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(btn_Back, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(109, 109, 109)
                        .addComponent(btn_OK, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(jLabel1)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_Tai_Khoan_Nhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_So_Tien_Chuyen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_Back, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                    .addComponent(btn_OK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BackActionPerformed
        User t = new User();
        t.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_BackActionPerformed

    private void btn_OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_OKActionPerformed

        if (txt_Tai_Khoan_Nhan.getText() != null && !(txt_Tai_Khoan_Nhan.getText()).trim().isEmpty()) {
            if ((txt_Tai_Khoan_Nhan.getText()).compareTo(tenTK) != 0) {
                if (KiemTraTaiKhoan(txt_Tai_Khoan_Nhan.getText()) == 0) {
                    JOptionPane.showMessageDialog(this, "Tài khoản nhận tiền không tồn tại !!!!");
                    txt_Tai_Khoan_Nhan.requestFocus();
                } else {
                    if (txt_So_Tien_Chuyen.getText() != null && !(txt_So_Tien_Chuyen.getText()).trim().isEmpty()) {
                        try {
                            if (Float.parseFloat(txt_So_Tien_Chuyen.getText()) < SoTienTrongTaiKhoan()) {
                                if (Float.parseFloat(txt_So_Tien_Chuyen.getText()) > 50000 && Float.parseFloat(txt_So_Tien_Chuyen.getText()) % 2 == 0) {
                                    ConnectionDB con = new ConnectionDB();
                                    String sql = "update UserN set SoTienTaiKhoan='" + (SoTienTrongTaiKhoan() - Float.parseFloat(txt_So_Tien_Chuyen.getText())) + "'  where username='" + l.user_dang_nhap + "'";
                                    int dialogButtons = JOptionPane.YES_NO_CANCEL_OPTION;
                                    int dl = JOptionPane.showConfirmDialog(this, "Bạn có muốn chuyển tiền không?", "Thông báo", dialogButtons);
                                    if (dl == 0) {
                                        con.s.executeUpdate(sql);
                                        Date date = java.util.Calendar.getInstance().getTime();
                                        con.s.executeUpdate("Insert Chuyentien values('" + date + "','" + tenTK + "','" + txt_Tai_Khoan_Nhan.getText() + "','" + Float.parseFloat(txt_So_Tien_Chuyen.getText()) + "')");
                                        con.s.executeUpdate("Insert Nhantien values('" + date + "','" + txt_Tai_Khoan_Nhan.getText() + "','" + tenTK + "','" + Float.parseFloat(txt_So_Tien_Chuyen.getText()) + "')");
                                        JOptionPane.showMessageDialog(this, "Bạn đã chuyển tiền thành công!!");
                                        txt_Tai_Khoan_Nhan.setText("");
                                        txt_So_Tien_Chuyen.setText("");
                                        txt_Tai_Khoan_Nhan.requestFocus();
                                    }

                                } else {
                                    JOptionPane.showMessageDialog(this, "Số tiền cần chuyển phải lớn hơn 50000 và là bội của 50000!!");
                                    txt_So_Tien_Chuyen.requestFocus();
                                }
                            } else {
                                JOptionPane.showMessageDialog(this, "Số tiền trong tài khoản không đủ để thực hiện giao dịch!!");
                                txt_So_Tien_Chuyen.requestFocus();
                            }

                        } catch (Exception e) {
                            JOptionPane.showMessageDialog(this, "Loi " + e);
                        }
                    } else {
                        JOptionPane.showMessageDialog(this, "Bạn phải nhập số tiền mới thực hiện thao tác này!!");
                        txt_Tai_Khoan_Nhan.requestFocus();
                    }
                }
            } else {
                JOptionPane.showMessageDialog(this, "Tài khoản nhận tiền không thể trùng với tài khoản của bạn !!");
                txt_Tai_Khoan_Nhan.requestFocus();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Bạn phải nhập tài khoản nhận tiền trước!!");
            txt_Tai_Khoan_Nhan.requestFocus();
        }
    }//GEN-LAST:event_btn_OKActionPerformed

    private void txt_So_Tien_ChuyenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_So_Tien_ChuyenMouseClicked

    }//GEN-LAST:event_txt_So_Tien_ChuyenMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Chuyen_Tien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Chuyen_Tien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Chuyen_Tien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Chuyen_Tien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Chuyen_Tien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Back;
    private javax.swing.JButton btn_OK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txt_So_Tien_Chuyen;
    private javax.swing.JTextField txt_Tai_Khoan_Nhan;
    // End of variables declaration//GEN-END:variables
}
