/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package doan;

import java.sql.ResultSet;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author phong
 */
public class Nap_Tien_Tai_Khoan extends javax.swing.JFrame {

    Login l = new Login();
    private String tenTK = l.user_dang_nhap;

    public Nap_Tien_Tai_Khoan() {
        initComponents();
    }

    public float SoTienTrongTaiKhoan() {
        float fTien = 0;
        try {
            ConnectionDB con = new ConnectionDB();
            String sql = "select * from UserN where username='" + tenTK + "'";

            ResultSet rs = con.s.executeQuery(sql);
            while (rs.next()) {
                fTien = Float.parseFloat(rs.getString("SoTienTaiKhoan"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Loi " + e);
        }
        return fTien;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btn_50 = new javax.swing.JButton();
        btn_200 = new javax.swing.JButton();
        btn_100 = new javax.swing.JButton();
        btn_500 = new javax.swing.JButton();
        btn_Back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Nạp Tiền Tài Khoản");

        btn_50.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_50.setText("50.000");
        btn_50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_50ActionPerformed(evt);
            }
        });

        btn_200.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_200.setText("200.000");
        btn_200.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_200ActionPerformed(evt);
            }
        });

        btn_100.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_100.setText("100.000");
        btn_100.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_100ActionPerformed(evt);
            }
        });

        btn_500.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_500.setText("500.000");
        btn_500.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_500ActionPerformed(evt);
            }
        });

        btn_Back.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_Back.setText("Back");
        btn_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_Back, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_200, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                                .addComponent(btn_500, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_50, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_100, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(60, 60, 60))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_50, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_100, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_500, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_200, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(btn_Back, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BackActionPerformed
        User u = new User();
        u.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_BackActionPerformed

    private void btn_50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_50ActionPerformed
        try {

            ConnectionDB con = new ConnectionDB();
            String sql = "update UserN set SoTienTaiKhoan='" + (SoTienTrongTaiKhoan() + 50000) + "'  where username='" + l.user_dang_nhap + "'";
            int dialogButtons = JOptionPane.YES_NO_CANCEL_OPTION;
            int dl = JOptionPane.showConfirmDialog(this, "Bạn có muốn nạp thêm tiền vào tài khoản không?", "Thông báo", dialogButtons);
            if (dl == 0) {
                con.s.executeUpdate(sql);
                JOptionPane.showMessageDialog(this, "Bạn đã nạp tiền thành công!!");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Loi " + e);
        }
    }//GEN-LAST:event_btn_50ActionPerformed

    private void btn_100ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_100ActionPerformed
         try {

            ConnectionDB con = new ConnectionDB();
            String sql = "update UserN set SoTienTaiKhoan='" + (SoTienTrongTaiKhoan() + 100000) + "'  where username='" + l.user_dang_nhap + "'";
            int dialogButtons = JOptionPane.YES_NO_CANCEL_OPTION;
            int dl = JOptionPane.showConfirmDialog(this, "Bạn có muốn nạp thêm tiền vào tài khoản không?", "Thông báo", dialogButtons);
            if (dl == 0) {
                con.s.executeUpdate(sql);
                JOptionPane.showMessageDialog(this, "Bạn đã nạp tiền thành công!!");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Loi " + e);
        }
    }//GEN-LAST:event_btn_100ActionPerformed

    private void btn_200ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_200ActionPerformed
         try {

            ConnectionDB con = new ConnectionDB();
            String sql = "update UserN set SoTienTaiKhoan='" + (SoTienTrongTaiKhoan() + 200000) + "'  where username='" + l.user_dang_nhap + "'";
            int dialogButtons = JOptionPane.YES_NO_CANCEL_OPTION;
            int dl = JOptionPane.showConfirmDialog(this, "Bạn có muốn nạp thêm tiền vào tài khoản không?", "Thông báo", dialogButtons);
            if (dl == 0) {
                con.s.executeUpdate(sql);
                JOptionPane.showMessageDialog(this, "Bạn đã nạp tiền thành công!!");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Loi " + e);
        }
    }//GEN-LAST:event_btn_200ActionPerformed

    private void btn_500ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_500ActionPerformed
         try {

            ConnectionDB con = new ConnectionDB();
            String sql = "update UserN set SoTienTaiKhoan='" + (SoTienTrongTaiKhoan() + 500000) + "'  where username='" + l.user_dang_nhap + "'";
            int dialogButtons = JOptionPane.YES_NO_CANCEL_OPTION;
            int dl = JOptionPane.showConfirmDialog(this, "Bạn có muốn nạp thêm tiền vào tài khoản không?", "Thông báo", dialogButtons);
            if (dl == 0) {
                con.s.executeUpdate(sql);
                JOptionPane.showMessageDialog(this, "Bạn đã nạp tiền thành công!!");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Loi " + e);
        }
    }//GEN-LAST:event_btn_500ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Nap_Tien_Tai_Khoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Nap_Tien_Tai_Khoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Nap_Tien_Tai_Khoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Nap_Tien_Tai_Khoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Nap_Tien_Tai_Khoan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_100;
    private javax.swing.JButton btn_200;
    private javax.swing.JButton btn_50;
    private javax.swing.JButton btn_500;
    private javax.swing.JButton btn_Back;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
