/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package doan;

import java.sql.ResultSet;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author phong
 */
public class Rut_Tien extends javax.swing.JFrame {

    Login l = new Login();
    private String tenTK = l.user_dang_nhap;

    public Rut_Tien() {
        initComponents();
    }

    public float SoTienTrongTaiKhoan() {
        float fTien = 0;
        try {
            ConnectionDB con = new ConnectionDB();
            String sql = "select * from UserN where username='" + tenTK + "'";

            ResultSet rs = con.s.executeQuery(sql);
            while (rs.next()) {
                fTien = Float.parseFloat(rs.getString("SoTienTaiKhoan"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Loi " + e);
        }
        return fTien;
    }

    // Date date=java.util.Calendar.getInstance().getTime(); ngay gio hien tai
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btn_200 = new javax.swing.JButton();
        btn_500 = new javax.swing.JButton();
        btn_50 = new javax.swing.JButton();
        btn_100 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_SoTienRut = new javax.swing.JTextField();
        btn_Back = new javax.swing.JButton();
        btn_OK1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Rút Tiền");

        btn_200.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_200.setText("200.000");
        btn_200.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_200ActionPerformed(evt);
            }
        });

        btn_500.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_500.setText("500.000");
        btn_500.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_500ActionPerformed(evt);
            }
        });

        btn_50.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_50.setText("50.000");
        btn_50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_50ActionPerformed(evt);
            }
        });

        btn_100.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_100.setText("100.000");
        btn_100.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_100ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Hoặc");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Nhập số tiền cần rút:");

        txt_SoTienRut.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        btn_Back.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_Back.setText("Back");
        btn_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BackActionPerformed(evt);
            }
        });

        btn_OK1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_OK1.setText("OK");
        btn_OK1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_OK1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(btn_50, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
                                .addComponent(btn_100, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(btn_200, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_500, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(53, 53, 53)
                                        .addComponent(btn_Back, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(28, 28, 28)
                                .addComponent(txt_SoTienRut)))
                        .addGap(103, 103, 103))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(330, Short.MAX_VALUE)
                    .addComponent(btn_OK1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(93, 93, 93)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_100, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_50, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_200, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_500, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jLabel2)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_SoTienRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(btn_Back, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(339, Short.MAX_VALUE)
                    .addComponent(btn_OK1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(15, 15, 15)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_OK1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_OK1ActionPerformed
        try {
            if (txt_SoTienRut.getText() != null && !(txt_SoTienRut.getText()).trim().isEmpty()) {
                if (Float.parseFloat(txt_SoTienRut.getText()) < SoTienTrongTaiKhoan()) {
                    if (Float.parseFloat(txt_SoTienRut.getText()) > 50000 && Float.parseFloat(txt_SoTienRut.getText()) % 2 == 0) {
                        ConnectionDB con = new ConnectionDB();
                        String sql = "update UserN set SoTienTaiKhoan='" + (SoTienTrongTaiKhoan() - Float.parseFloat(txt_SoTienRut.getText())) + "'  where username='" + l.user_dang_nhap + "'";
                        int dialogButtons = JOptionPane.YES_NO_CANCEL_OPTION;
                        int dl = JOptionPane.showConfirmDialog(this, "Bạn có muốn rút tiền không?", "Thông báo", dialogButtons);
                        if (dl == 0) {
                            con.s.executeUpdate(sql);
                            Date date = java.util.Calendar.getInstance().getTime();
                            con.s.executeUpdate("Insert RutTien values('" + date + "','" + tenTK + "','" + Float.parseFloat(txt_SoTienRut.getText()) + "')");
                            JOptionPane.showMessageDialog(this, "Bạn đã rút tiền thành công!!");
                            txt_SoTienRut.setText("");
                        }

                    } else {
                        JOptionPane.showMessageDialog(this, "Số tiền cần rút phải lớn hơn 50000 và là bội của 50000!!");
                        txt_SoTienRut.requestFocus();
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Số tiền trong tài khoản không đủ để thực hiện giao dịch!!");
                    txt_SoTienRut.requestFocus();
                }
            } else {
                JOptionPane.showMessageDialog(this, "Bạn phải nhập Số tiền rút  trước!!");
                txt_SoTienRut.requestFocus();
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Loi " + e);
        }
    }//GEN-LAST:event_btn_OK1ActionPerformed

    private void btn_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BackActionPerformed
        User t = new User();
        t.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_BackActionPerformed

    private void btn_50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_50ActionPerformed
        try {
            if (SoTienTrongTaiKhoan() > 50000) {
                ConnectionDB con = new ConnectionDB();
                String sql = "update UserN set SoTienTaiKhoan='" + (SoTienTrongTaiKhoan() - 50000) + "'  where username='" + l.user_dang_nhap + "'";
                int dialogButtons = JOptionPane.YES_NO_CANCEL_OPTION;
                int dl = JOptionPane.showConfirmDialog(this, "Bạn có muốn rút tiền không?", "Thông báo", dialogButtons);
                if (dl == 0) {
                    con.s.executeUpdate(sql);
                    Date date = java.util.Calendar.getInstance().getTime();
                    con.s.executeUpdate("Insert RutTien values('" + date + "','" + tenTK + "','" + 50000 + "')");
                    JOptionPane.showMessageDialog(this, "Bạn đã rút tiền thành công!!");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Số tiền trong tài khoản không đủ để thực hiện giao dịch!!");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Loi " + e);
        }
    }//GEN-LAST:event_btn_50ActionPerformed

    private void btn_100ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_100ActionPerformed
        try {
            if (SoTienTrongTaiKhoan() > 100000) {
                ConnectionDB con = new ConnectionDB();
                String sql = "update UserN set SoTienTaiKhoan='" + (SoTienTrongTaiKhoan() - 100000) + "'  where username='" + l.user_dang_nhap + "'";
                int dialogButtons = JOptionPane.YES_NO_CANCEL_OPTION;
                int dl = JOptionPane.showConfirmDialog(this, "Bạn có muốn rút tiền không?", "Thông báo", dialogButtons);
                if (dl == 0) {
                    con.s.executeUpdate(sql);
                    Date date = java.util.Calendar.getInstance().getTime();
                    con.s.executeUpdate("Insert RutTien values('" + date + "','" + tenTK + "','" + 100000 + "')");
                    JOptionPane.showMessageDialog(this, "Bạn đã rút tiền thành công!!");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Số tiền trong tài khoản không đủ để thực hiện giao dịch!!");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Loi " + e);
        }
    }//GEN-LAST:event_btn_100ActionPerformed

    private void btn_200ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_200ActionPerformed
        try {
            if (SoTienTrongTaiKhoan() > 200000) {
                ConnectionDB con = new ConnectionDB();
                String sql = "update UserN set SoTienTaiKhoan='" + (SoTienTrongTaiKhoan() - 200000) + "'  where username='" + l.user_dang_nhap + "'";
                int dialogButtons = JOptionPane.YES_NO_CANCEL_OPTION;
                int dl = JOptionPane.showConfirmDialog(this, "Bạn có muốn rút tiền không?", "Thông báo", dialogButtons);
                if (dl == 0) {
                    con.s.executeUpdate(sql);
                    Date date = java.util.Calendar.getInstance().getTime();
                    con.s.executeUpdate("Insert RutTien values('" + date + "','" + tenTK + "','" + 200000 + "')");
                    JOptionPane.showMessageDialog(this, "Bạn đã rút tiền thành công!!");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Số tiền trong tài khoản không đủ để thực hiện giao dịch!!");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Loi " + e);
        }
    }//GEN-LAST:event_btn_200ActionPerformed

    private void btn_500ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_500ActionPerformed
        try {
            if (SoTienTrongTaiKhoan() > 500000) {
                ConnectionDB con = new ConnectionDB();
                String sql = "update UserN set SoTienTaiKhoan='" + (SoTienTrongTaiKhoan() - 500000) + "'  where username='" + l.user_dang_nhap + "'";
                int dialogButtons = JOptionPane.YES_NO_CANCEL_OPTION;
                int dl = JOptionPane.showConfirmDialog(this, "Bạn có muốn rút tiền không?", "Thông báo", dialogButtons);
                if (dl == 0) {
                    con.s.executeUpdate(sql);
                    Date date = java.util.Calendar.getInstance().getTime();
                    con.s.executeUpdate("Insert RutTien values('" + date + "','" + tenTK + "','" + 500000 + "')");
                    JOptionPane.showMessageDialog(this, "Bạn đã rút tiền thành công!!");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Số tiền trong tài khoản không đủ để thực hiện giao dịch!!");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Loi " + e);
        }
    }//GEN-LAST:event_btn_500ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Rut_Tien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Rut_Tien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Rut_Tien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Rut_Tien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Rut_Tien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_100;
    private javax.swing.JButton btn_200;
    private javax.swing.JButton btn_50;
    private javax.swing.JButton btn_500;
    private javax.swing.JButton btn_Back;
    private javax.swing.JButton btn_OK1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txt_SoTienRut;
    // End of variables declaration//GEN-END:variables
}
