/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package doan;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author phong
 */
public class User extends javax.swing.JFrame {
    
    /**
     * Creates new form User
     */
    public User() {
        initComponents();
        Login l=new Login();
        txt_Ten_TK.setText("Xin chào tài khoản "+l.user_dang_nhap+" đến với dịch vụ ATM");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_Ten_TK = new javax.swing.JLabel();
        btn_Rut_Tien = new javax.swing.JButton();
        btn_Xem_Thong_Tin_Tai_Khoan = new javax.swing.JButton();
        btn_Thoat = new javax.swing.JButton();
        btn_Doi_Mat_Khau = new javax.swing.JButton();
        btn_Chuyen_Tien = new javax.swing.JButton();
        btn_Lich_Su = new javax.swing.JButton();
        btn_NapTien = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txt_Ten_TK.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txt_Ten_TK.setForeground(new java.awt.Color(255, 0, 0));
        txt_Ten_TK.setText("tên tài khoản");

        btn_Rut_Tien.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_Rut_Tien.setText("Rút Tiền");
        btn_Rut_Tien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Rut_TienActionPerformed(evt);
            }
        });

        btn_Xem_Thong_Tin_Tai_Khoan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_Xem_Thong_Tin_Tai_Khoan.setText("Xem Thông tin tài khoản");
        btn_Xem_Thong_Tin_Tai_Khoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Xem_Thong_Tin_Tai_KhoanActionPerformed(evt);
            }
        });

        btn_Thoat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_Thoat.setText("Đăng xuất");
        btn_Thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThoatActionPerformed(evt);
            }
        });

        btn_Doi_Mat_Khau.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_Doi_Mat_Khau.setText("Đổi mật khẩu");
        btn_Doi_Mat_Khau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Doi_Mat_KhauActionPerformed(evt);
            }
        });

        btn_Chuyen_Tien.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_Chuyen_Tien.setText("Chuyển Tiền");
        btn_Chuyen_Tien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Chuyen_TienActionPerformed(evt);
            }
        });

        btn_Lich_Su.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_Lich_Su.setText("Lịch sử giao dịch");
        btn_Lich_Su.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Lich_SuActionPerformed(evt);
            }
        });

        btn_NapTien.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_NapTien.setText("Nạp Tiền Tài Khoản");
        btn_NapTien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NapTienActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_Xem_Thong_Tin_Tai_Khoan)
                        .addGap(100, 100, 100)
                        .addComponent(btn_Rut_Tien, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_Chuyen_Tien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_Lich_Su, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE))
                        .addGap(100, 100, 100)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_Doi_Mat_Khau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_NapTien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(58, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(txt_Ten_TK)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_Thoat)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_Ten_TK)
                    .addComponent(btn_Thoat, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Xem_Thong_Tin_Tai_Khoan, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Rut_Tien, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addComponent(btn_Doi_Mat_Khau, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_Lich_Su, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_NapTien, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(btn_Chuyen_Tien, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_Xem_Thong_Tin_Tai_KhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Xem_Thong_Tin_Tai_KhoanActionPerformed
        Thong_Tin_Tai_Khoan t = new Thong_Tin_Tai_Khoan();
        t.setVisible(true);
        this.setVisible(false);
       
    }//GEN-LAST:event_btn_Xem_Thong_Tin_Tai_KhoanActionPerformed

    private void btn_Rut_TienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Rut_TienActionPerformed
        Rut_Tien rt=new Rut_Tien();
         rt.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_Rut_TienActionPerformed

    private void btn_Lich_SuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Lich_SuActionPerformed
        Lich_Su_Giao_Dich ls=new Lich_Su_Giao_Dich();
         ls.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_Lich_SuActionPerformed

    private void btn_Chuyen_TienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Chuyen_TienActionPerformed
        Chuyen_Tien ct=new Chuyen_Tien();
         ct.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_Chuyen_TienActionPerformed

    private void btn_Doi_Mat_KhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Doi_Mat_KhauActionPerformed
        Doi_Mat_Khau dmk=new Doi_Mat_Khau();
         dmk.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_Doi_Mat_KhauActionPerformed

    private void btn_ThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThoatActionPerformed
        Login l =new Login();
         l.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_ThoatActionPerformed

    private void btn_NapTienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_NapTienActionPerformed
        Nap_Tien_Tai_Khoan ntk=new Nap_Tien_Tai_Khoan();
        ntk.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_NapTienActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new User().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Chuyen_Tien;
    private javax.swing.JButton btn_Doi_Mat_Khau;
    private javax.swing.JButton btn_Lich_Su;
    private javax.swing.JButton btn_NapTien;
    private javax.swing.JButton btn_Rut_Tien;
    private javax.swing.JButton btn_Thoat;
    private javax.swing.JButton btn_Xem_Thong_Tin_Tai_Khoan;
    private javax.swing.JLabel txt_Ten_TK;
    // End of variables declaration//GEN-END:variables
}
